<?php
$Bok_kprodimmo_insert = false;

$prepared_query = 'SELECT id_page FROM product
                   WHERE id_page = :id';
if((checkrights($main_rights_log, '9', $redirection)) === true){ $_SESSION['prepared_query'] = $prepared_query; }
$query = $connectData->prepare($prepared_query);
$query->bindParam('id', $selected_product);
$query->execute();

if(($data = $query->fetch()) == false)
{
    $Bok_kprodimmo_insert = true;
}
$query->closeCursor();

if($Bok_kprodimmo_insert == false) #update
{
    $prepared_query = 'UPDATE product
                       SET offer_product_immo = :offer_general,
                           ref_product_immo = :reference_general,
                           type_product_immo = :type_general,
                           price_product_immo = :price_general,
                           currency_product_immo = :currency_general,
                           feeamount_product_immo = :feeamount_general,
                           feetype_product_immo = :feetype_general,
                           feeincex_product_immo = :feeincex_general,
                           surfacehab_product_immo = :surfacehab_general,
                           surfaceground_product_immo = :surfaceground_general,
                           surfacegroundm2_product_immo = :surfacegroundm2_general,
                           surfacegroundmeasure_product_immo = :surfacegroundmeasure_general,
                           cellar_product_immo = :cellar_general,
                           loft_product_immo = :loft_general,
                           levelnb_product_immo = :levelnb_general,
                           piecesnb_product_immo = :piecesnb_general,
                           sleepnb_product_immo = :sleepnb_general,
                           bathnb_product_immo = :bathnb_general,
                           wcnb_product_immo = :wcnb_general,
                           outhousesnb_product_immo = :outhousesnb_general,
                           condition_product_immo = :condition_general,
                           dpe_product_immo = :dpe_energy,
                           ges_product_immo = :ges_energy,
                           heating_product_immo = :heating_energy,
                           heatingother_product_immo = :heatingother_energy,
                           insulation_product_immo = :insulation_energy,
                           window_product_immo = :window_energy,
                           water_product_immo = :water_other,
                           power_product_immo = :product_other,
                           phone_product_immo = :phone_other,
                           tv_product_immo = :tv_other,
                           internet_product_immo = :internet_other,
                           furnished_product_immo = :furnished_other,
                           agency_product_immo = NULL,
                           comdetails_product_immo = :comdetails_admin,
                           remarks_product_immo = :remarks_admin,
                           latitude_product_immo = :lat_situation,
                           longitude_product_immo = :long_situation,
                           country_product_immo = :country_situation,
                           region_product_immo = :region_situation,
                           department_product_immo = :department_situation,
                           district_product_immo = :district_situation,
                           city_product_immo = :city_situation,
                           zip_product_immo = :zip_situation,
                           location_product_immo = :location_situation,
                           locdetails_product_immo = :locdetails_situation,
                           facilitiesorder_product_immo = :facilitiesorder_situation,
                           facilities_product_immo = :facilities_situation,
                           facilitiesdistance_product_immo = :facilitiesdistance_situation,
                           facilitiesgroup_product_immo = :facilitiesgroup_situation,
                           interior_product_immo = :interior,
                           exterior_product_immo = :exterior,
                           exteriorother_product_immo = :exteriorother
                       WHERE id_page = :id_page';
    if((checkrights($main_rights_log, '9', $redirection)) === true){ $_SESSION['prepared_query'] = $prepared_query; }
    $query = $connectData->prepare($prepared_query);
    $query->execute(array(
                           'offer_general' => $kprodimmo_offer_general,
                           'reference_general' => $kprodimmo_reference_general,
                           'type_general' => $kprodimmo_type_general,
                           'price_general' => $kprodimmo_price_general,
                           'currency_general' => $kprodimmo_currency_general,
                           'feeamount_general' => $kprodimmo_fee_general,
                           'feetype_general' => $kprodimmo_feetype_general,
                           'feeincex_general' => $kprodimmo_feeincex_general,
                           'surfacehab_general' => $kprodimmo_surfacehab_general,
                           'surfaceground_general' => $kprodimmo_surfaceground_general,
                           'surfacegroundm2_general' => $kprodimmo_surfacegroundm2_general,
                           'surfacegroundmeasure_general' => $kprodimmo_surfacetype_general,
                           'cellar_general' => $kprodimmo_surfacecellar_general,
                           'loft_general' => $kprodimmo_surfaceloft_general,
                           'levelnb_general' => $kprodimmo_numfloor_general,
                           'piecesnb_general' => $kprodimmo_numrooms_general,
                           'sleepnb_general' => $kprodimmo_numsleeps_general,
                           'bathnb_general' => $kprodimmo_numbath_general,
                           'wcnb_general' => $kprodimmo_numwc_general,
                           'outhousesnb_general' => $kprodimmo_numouthouses_general,
                           'condition_general' => $kprodimmo_condition_general,
                           'dpe_energy' => $kprodimmo_dpe_energy,
                           'ges_energy' => $kprodimmo_ges_energy,
                           'heating_energy' => $kprodimmo_heating_energy,
                           'heatingother_energy' => $kprodimmo_heatingother_energy,
                           'insulation_energy' => $kprodimmo_isolation_energy,
                           'window_energy' => $kprodimmo_window_energy,
                           'water_other' => $kprodimmo_water_other,
                           'product_other' => $kprodimmo_power_other,
                           'phone_other' => $kprodimmo_phone_other,
                           'tv_other' => $kprodimmo_tv_other,
                           'internet_other' => $kprodimmo_internet_other,
                           'furnished_other' => $kprodimmo_furnished_other,
                           'comdetails_admin' => $kprodimmo_comdetails_admin,
                           'remarks_admin' => $kprodimmo_note_admin,
                           'lat_situation' => $kprodimmo_latitude_situation,
                           'long_situation' => $kprodimmo_longitude_situation,
                           'country_situation' => $kprodimmo_country_situation,
                           'region_situation' => $kprodimmo_region_situation,
                           'department_situation' => $kprodimmo_department_situation,
                           'district_situation' => $kprodimmo_district_situation,
                           'city_situation' => $Kprodimmo_idcity_situation,
                           'zip_situation' => $Kprodimmo_zipcity_situation,
                           'location_situation' => $kprodimmo_location_situation,
                           'locdetails_situation' => $kprodimmo_locdetails_situation,
                           'facilitiesorder_situation' => $kprodimmo_facilitiesorder_situation,
                           'facilities_situation' => $kprodimmo_facilities_situation,
                           'facilitiesdistance_situation' => $kprodimmo_facilitiesdistance_situation,
                           'facilitiesgroup_situation' => $kprodimmo_facilitiesgroup_situation,
                           'interior' => $kprodimmo_piecesin_interior,
                           'exterior' => $kprodimmo_piecesout_exterior,
                           'exteriorother' => $kprodimmo_other_exterior,
                           'id_page' => $selected_product
                          ));
    $query->closeCursor();
}
else #insert
{

	$prepared_query = 'INSERT INTO product
                       (status_product,
					    number_product,
					    code_product_L1, 
						code_product_L2, 
						code_product_L3, 
						code_product_L4,
						code_product_L5,
						name_product_L1,
						name_product_L2,
						name_product_L3,
						name_product_L4,
						name_product_L5,
						introduction_product_L1,
						introduction_product_L2,
						introduction_product_L3,
						introduction_product_L4,
						introduction_product_L5,
						description_product_L1,
						description_product_L2,
						description_product_L3,
						description_product_L4,
						description_product_L5,
						code_group_product,
						code_category_product,
						id_option_product,
						priority_product,
						image_thumb_product,
						id_page,
						number_link_product,
						cart_type_product,
						transport_fee_product,
						noticelink_product,
						id_cooshop,
						product_class_id) 
                   VALUES
                        (:product_status,
						 :product_number,
						 :product_code_L1,
                         :product_code_L2,
                         :product_code_L3,
                         :product_code_L4,
						 :product_code_L5,
						 :product_name_L1,
						 :product_name_L2,
						 :product_name_L3,
						 :product_name_L4,
						 :product_name_L5,
						 :product_introduction_L1,
						 :product_introduction_L2,
						 :product_introduction_L3,
						 :product_introduction_L4,
						 :product_introduction_L5,
						 :product_description_L1,
						 :product_description_L2,
						 :product_description_L3,
						 :product_description_L4,
						 :product_description_L5,
						 :product_group_code,
						 :product_category_code,
						 :product_option_id,
						 :product_priority,
						 :product_image_thumb,
						 :page_id,
						 :product_link_number,
						 :product_cart_type,
						 :product_transport_fee,
						 :product_noticelink,
						 :cooshop_id,
						 :class_id_product)';
    /*$prepared_query = 'INSERT INTO product
                           (id_page, ref_product_immo, 
                            type_product_immo,
                            price_product_immo, 
                            currency_product_immo , 
                            feeamount_product_immo,
                            feetype_product_immo,
                            feeincex_product_immo,
                            surfacehab_product_immo,
                            surfaceground_product_immo,
                            surfacegroundmeasure_product_immo,
                            cellar_product_immo,
                            loft_product_immo,
                            levelnb_product_immo,
                            piecesnb_product_immo,
                            sleepnb_product_immo,
                            bathnb_product_immo,
                            wcnb_product_immo,
                            outhousesnb_product_immo,
                            condition_product_immo,
                            dpe_product_immo,
                            ges_product_immo,
                            heating_product_immo,
                            heatingother_product_immo,
                            insulation_product_immo,
                            window_product_immo,
                            water_product_immo,
                            power_product_immo,
                            phone_product_immo,
                            tv_product_immo,
                            internet_product_immo,
                            furnished_product_immo,
                            agency_product_immo,
                            comdetails_product_immo,
                            remarks_product_immo,
                            latitude_product_immo,
                            longitude_product_immo,
                            country_product_immo,
                            region_product_immo,
                            department_product_immo,
                            district_product_immo,
                            city_product_immo,
                            zip_product_immo,
                            location_product_immo,
                            locdetails_product_immo,
                            facilitiesorder_product_immo,
                            facilities_product_immo,
                            facilitiesdistance_product_immo,
                            facilitiesgroup_product_immo,
                            interior_product_immo,
                            exterior_product_immo,
                            exteriorother_product_immo)
                       VALUES
                            (:id_page,
                             :reference_general,
                             :type_general,
                             :price_general,
                             :currency_general,
                             :feeamount_general,
                             :feetype_general,
                             :feeincex_general,
                             :surfacehab_general,
                             :surfaceground_general,
                             :surfacegroundmeasure_general,
                             :cellar_general,
                             :loft_general,
                             :levelnb_general,
                             :piecesnb_general,
                             :sleepnb_general,
                             :bathnb_general,
                             :wcnb_general,
                             :outhousesnb_general,
                             :condition_general,
                             :dpe_energy,
                             :ges_energy,
                             :heating_energy,
                             :heatingother_energy,
                             :insulation_energy,
                             :window_energy,
                             :water_other,
                             :product_other,
                             :phone_other,
                             :tv_other,
                             :internet_other,
                             :furnished_other,
                             NULL,
                             :comdetails_admin,
                             :remarks_admin,
                             :lat_situation,
                             :long_situation,
                             :country_situation,
                             :region_situation,
                             :department_situation,
                             :district_situation,
                             :city_situation,
                             :zip_situation,
                             :location_situation,
                             :locdetails_situation,
                             :facilitiesorder_situation,
                             :facilities_situation,
                             :facilitiesdistance_situation,
                             :facilitiesgroup_situation,
                             :interior,
                             :exterior,
                             :exteriorother)';*/
    if((checkrights($main_rights_log, '9', $redirection)) === true){ $_SESSION['prepared_query'] = $prepared_query; }
    $query = $connectData->prepare($prepared_query);
	$query->execute(array(
                         'product_status'  => $_POST['cboProductStatus'],
						 'product_number'  => $_POST['number_product'],
						 'product_code_L1' => " ",//$product_code_L1,
                         'product_code_L2' => " ",//$product_code_L2,
                         'product_code_L3' => " ",//$product_code_L3,
                         'product_code_L4' => " ",//$product_code_L4,
						 'product_code_L5' => " ",//$product_code_L5,
						 'product_name_L1' => " ",//$product_name_L1,
						 'product_name_L2' => " ",//$product_name_L2,
						 'product_name_L3' => " ",//$product_name_L3,
						 'product_name_L4' => " ",//$product_name_L4,
						 'product_name_L5' => " ",//$product_name_L5,
						 'product_introduction_L1' => " ",//$product_introduction_L1,
						 'product_introduction_L2' => " ",//$product_introduction_L2,
						 'product_introduction_L3' => " ",//$product_introduction_L3,
						 'product_introduction_L4' => " ",//$product_introduction_L4,
						 'product_introduction_L5' => " ",//$product_introduction_L5,
						 'product_description_L1' => " ",//$product_description_L1,
						 'product_description_L2' => " ",//$product_description_L2,
						 'product_description_L3' => " ",//$product_description_L3,
						 'product_description_L4' => " ",//$product_description_L4,
						 'product_description_L5' => " ",//$product_description_L5,
						 'product_group_code' => " ",//$product_group_code,
						 'product_category_code' => " ",//$product_category_code,
						 'product_option_id' => " ",//$product_option_id,
						 'product_priority'      => $product_priority,
						 'product_image_thumb'   => " ",//$product_image_thumb,
						 'page_id'               => $selected_product,
						 'product_link_number' => " ",//$product_link_number,
						 'product_cart_type' => " ",//$product_cart_type,
						 'product_transport_fee' => " ",//$product_transport_fee,
						 'product_noticelink' => " ",//$product_noticelink,
						 'cooshop_id' => " ",//$cooshop_id,
						 'class_id_product' => " "//$class_id_product
                      ));
    $query->closeCursor();
}
?>                     