<?php
$prepared_query = 'INSERT INTO product
                       (status_product,
					    number_product,
					    code_product_L1, 
						code_product_L2, 
						code_product_L3, 
						code_product_L4,
						code_product_L5,
						name_product_L1,
						name_product_L2,
						name_product_L3,
						name_product_L4,
						name_product_L5,
						introduction_product_L1,
						introduction_product_L2,
						introduction_product_L3,
						introduction_product_L4,
						introduction_product_L5,
						description_product_L1,
						description_product_L2,
						description_product_L3,
						description_product_L4,
						description_product_L5,
						code_group_product,
						code_category_product,
						id_option_product,
						priority_product,
						image_thumb_product,
						id_page,
						number_link_product,
						cart_type_product,
						transport_fee_product,
						noticelink_product,
						id_cooshop,
						product_class_id) 
                   VALUES
                        (:product_status,
						 :product_number,
						 :product_code_L1,
                         :product_code_L2,
                         :product_code_L3,
                         :product_code_L4,
						 :product_code_L5,
						 :product_name_L1,
						 :product_name_L2,
						 :product_name_L3,
						 :product_name_L4,
						 :product_name_L5,
						 :product_introduction_L1,
						 :product_introduction_L2,
						 :product_introduction_L3,
						 :product_introduction_L4,
						 :product_introduction_L5,
						 :product_description_L1,
						 :product_description_L2,
						 :product_description_L3,
						 :product_description_L4,
						 :product_description_L5,
						 :product_group_code,
						 :product_category_code,
						 :product_option_id,
						 :product_priority,
						 :product_image_thumb,
						 :page_id,
						 :product_link_number,
						 :product_cart_type,
						 :product_transport_fee,
						 :product_noticelink,
						 :cooshop_id,
						 :class_id_product)';
if((checkrights($main_rights_log, '9', $redirection)) === true){ $_SESSION['prepared_query'] = $prepared_query; }
$query = $connectData->prepare($prepared_query);
$query->execute(array(
                         'product_status' => $product_status,
						 'product_number' => $product_number,
						 'product_code_L1' => $product_code_L1,
                         'product_code_L2' => $product_code_L2,
                         'product_code_L3' => $product_code_L3,
                         'product_code_L4' => $product_code_L4,
						 'product_code_L5' => $product_code_L5,
						 'product_name_L1' => $product_name_L1,
						 'product_name_L2' => $product_name_L2,
						 'product_name_L3' => $product_name_L3,
						 'product_name_L4' => $product_name_L4,
						 'product_name_L5' => $product_name_L5,
						 'product_introduction_L1' => $product_introduction_L1,
						 'product_introduction_L2' => $product_introduction_L2,
						 'product_introduction_L3' => $product_introduction_L3,
						 'product_introduction_L4' => $product_introduction_L4,
						 'product_introduction_L5' => $product_introduction_L5,
						 'product_description_L1' => $product_description_L1,
						 'product_description_L2' => $product_description_L2,
						 'product_description_L3' => $product_description_L3,
						 'product_description_L4' => $product_description_L4,
						 'product_description_L5' => $product_description_L5,
						 'product_group_code' => $product_group_code,
						 'product_category_code' => $product_category_code,
						 'product_option_id' => $product_option_id,
						 'product_priority' => $product_priority,
						 'product_image_thumb' => $product_image_thumb,
						 'page_id' => $page_id,
						 'product_link_number' => $product_link_number,
						 'product_cart_type' => $product_cart_type,
						 'product_transport_fee' => $product_transport_fee,
						 'product_noticelink' => $product_noticelink,
						 'cooshop_id' => $cooshop_id,
						 'class_id_product' => $class_id_product
                      ));
$query->closeCursor();
?>
